language: node.js
node_js:
  - 12

services:
  - docker

script:
  - docker --version
  - docker build ./udagram-api-feed -t udagram-api-feed -f udagram-api-feed/Dockerfile
  - docker tag udagram-api-feed andrewrisse/udagram-api-feed:latest
  - docker build ./udagram-api-users -t udagram-api-users -f udagram-api-users/Dockerfile
  - docker tag udagram-api-users andrewrisse/udagram-api-users:latest
  - docker build ./udagram-frontend -t udagram-frontend -f udagram-frontend/Dockerfile
  - docker tag udagram-frontend andrewrisse/udagram-frontend:latest
  - docker build ./reverse-proxy -t reverse-proxy -f reverse-proxy/Dockerfile
  - docker tag reverse-proxy andrewrisse/reverse-proxy:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push andrewrisse/udagram-api-feed
  - docker push andrewrisse/udagram-api-users
  - docker push andrewrisse/udagram-frontend
  - docker push andrewrisse/reverse-proxy
