language: node.js
node_js:
  - 12

services:
  - docker

script:
  - docker --version
  - docker build -t udagram-api-feed -f udagram-api-feed .
  - docker tag udagram-api-feed andrewrisse/udagram-api-feed:latest
  - docker build -t udagram-api-users -f udagram-api-users .
  - docker tag udagram-api-users andrewrisse/udagram-api-users:latest
  - docker build -t udagram-frontend -f udagram-frontend .
  - docker tag udagram-frontend andrewrisse/udagram-frontend:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push andrewrisse/udagram-api-feed
  - docker push andrewrisse/udagram-api-users
  - docker push andrewrisse/udagram-frontend
